### ISSUE TITLE
Dashboards with default filters don't load correctly

### ISSUE THREAD

**Issue by cjmccarthy** [newrelic-experimental/nr1-open-boards#5]
Filters appear in strange format in nrql:

nrql: "SELECT average(memoryUsedBytes), average(memoryLimitBytes) FROM K8sContainerSample TIMESERIES   WHERE appName,label.app.kubernetes.io/name,labels.app.kubernetes.io/name,event.involvedObject.name,deploymentName = 'ABC' WHERE clusterName = 'XYZ'  WHERE 1602644811509=1602644811509"

**Comment by Kav91** [comment]
Should be fixed now, will leave open till we confirm all looks good.

**Comment by cjmccarthy** [comment]
lgtm now
